services:
  chatbot:
    container_name: django-chatbot
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  
    environment:
      - DEBUG=True
    volumes:
      - .:/app
    networks:
      - chatbot_network

networks:
  chatbot_network:

